[2024-11-21T00:54:59.777+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-21T00:54:59.790+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_store_airbnb_data.scrape_airbnb_data manual__2024-11-20T21:46:19.565666+00:00 [queued]>
[2024-11-21T00:54:59.795+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_store_airbnb_data.scrape_airbnb_data manual__2024-11-20T21:46:19.565666+00:00 [queued]>
[2024-11-21T00:54:59.796+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-21T00:54:59.932+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_airbnb_data> on 2024-11-20 21:46:19.565666+00:00
[2024-11-21T00:54:59.940+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=107) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-21T00:54:59.941+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_store_airbnb_data', 'scrape_airbnb_data', 'manual__2024-11-20T21:46:19.565666+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpu4dy5l8e']
[2024-11-21T00:54:59.942+0000] {standard_task_runner.py:72} INFO - Started process 109 to run task
[2024-11-21T00:54:59.942+0000] {standard_task_runner.py:105} INFO - Job 63: Subtask scrape_airbnb_data
[2024-11-21T00:54:59.978+0000] {task_command.py:467} INFO - Running <TaskInstance: scrape_and_store_airbnb_data.scrape_airbnb_data manual__2024-11-20T21:46:19.565666+00:00 [running]> on host b3a8bb7dbe23
[2024-11-21T00:55:00.153+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scrape_and_store_airbnb_data' AIRFLOW_CTX_TASK_ID='scrape_airbnb_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-20T21:46:19.565666+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-20T21:46:19.565666+00:00'
[2024-11-21T00:55:00.154+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-21T00:55:00.154+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-21T00:55:00.154+0000] {logging_mixin.py:190} INFO - Current task name:scrape_airbnb_data state:running start_date:2024-11-21 00:54:59.790509+00:00
[2024-11-21T00:55:00.155+0000] {logging_mixin.py:190} INFO - Dag name:scrape_and_store_airbnb_data and current dag run status:running
[2024-11-21T00:55:00.155+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-21T00:55:40.299+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-11-21T00:55:40.299+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-21T00:55:40.301+0000] {process_utils.py:132} INFO - Sending 15 to group 109. PIDs of all processes in the group: [109]
[2024-11-21T00:55:40.301+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 109
[2024-11-21T00:55:40.302+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-21T00:55:40.310+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 39, in scrape_airbnb_data
    data = fetch_all_data(limit=100)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 33, in fetch_all_data
    time.sleep(0.5)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-11-21T00:55:40.316+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-21T00:55:40.316+0000] {logging_mixin.py:190} INFO - Task start:2024-11-21 00:54:59.790509+00:00 end:2024-11-21 00:55:40.315473+00:00 duration:40.524964
[2024-11-21T00:55:40.317+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): scrape_airbnb_data> dag:<DAG: scrape_and_store_airbnb_data> dagrun:<DagRun scrape_and_store_airbnb_data @ 2024-11-20 21:46:19.565666+00:00: manual__2024-11-20T21:46:19.565666+00:00, state:running, queued_at: 2024-11-21 00:54:57.449204+00:00. externally triggered: True>
[2024-11-21T00:55:40.317+0000] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2024-11-21T00:55:40.318+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=scrape_and_store_airbnb_data, task_id=scrape_airbnb_data, run_id=manual__2024-11-20T21:46:19.565666+00:00, execution_date=20241120T214619, start_date=20241121T005459, end_date=20241121T005540
[2024-11-21T00:55:40.327+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-21T00:55:40.354+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=109, status='terminated', exitcode=2, started='00:54:59') (109) terminated with exit code 2
