[2024-11-20T21:45:16.308+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-20T21:45:16.323+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_store_airbnb_data.scrape_airbnb_data manual__2024-11-20T21:30:27.250542+00:00 [queued]>
[2024-11-20T21:45:16.328+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_store_airbnb_data.scrape_airbnb_data manual__2024-11-20T21:30:27.250542+00:00 [queued]>
[2024-11-20T21:45:16.329+0000] {taskinstance.py:2866} INFO - Starting attempt 8 of 8
[2024-11-20T21:45:16.340+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_airbnb_data> on 2024-11-20 21:30:27.250542+00:00
[2024-11-20T21:45:16.348+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=179) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-20T21:45:16.350+0000] {standard_task_runner.py:72} INFO - Started process 181 to run task
[2024-11-20T21:45:16.349+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_store_airbnb_data', 'scrape_airbnb_data', 'manual__2024-11-20T21:30:27.250542+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpxh4jeh9w']
[2024-11-20T21:45:16.350+0000] {standard_task_runner.py:105} INFO - Job 54: Subtask scrape_airbnb_data
[2024-11-20T21:45:16.384+0000] {task_command.py:467} INFO - Running <TaskInstance: scrape_and_store_airbnb_data.scrape_airbnb_data manual__2024-11-20T21:30:27.250542+00:00 [running]> on host b70b34de9b89
[2024-11-20T21:45:16.733+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scrape_and_store_airbnb_data' AIRFLOW_CTX_TASK_ID='scrape_airbnb_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-20T21:30:27.250542+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-20T21:30:27.250542+00:00'
[2024-11-20T21:45:16.733+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-20T21:45:16.734+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-20T21:45:16.734+0000] {logging_mixin.py:190} INFO - Current task name:scrape_airbnb_data state:running start_date:2024-11-20 21:45:16.324441+00:00
[2024-11-20T21:45:16.734+0000] {logging_mixin.py:190} INFO - Dag name:scrape_and_store_airbnb_data and current dag run status:running
[2024-11-20T21:45:16.735+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-20T21:45:31.479+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-11-20T21:45:31.480+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-20T21:45:31.481+0000] {process_utils.py:132} INFO - Sending 15 to group 181. PIDs of all processes in the group: [181]
[2024-11-20T21:45:31.481+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 181
[2024-11-20T21:45:31.481+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-20T21:45:31.490+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 39, in scrape_airbnb_data
    data = fetch_all_data(limit=100)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 33, in fetch_all_data
    time.sleep(0.5)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-11-20T21:45:31.497+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-20T21:45:31.497+0000] {logging_mixin.py:190} INFO - Task start:2024-11-20 21:45:16.324441+00:00 end:2024-11-20 21:45:31.496698+00:00 duration:15.172257
[2024-11-20T21:45:31.498+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): scrape_airbnb_data> dag:<DAG: scrape_and_store_airbnb_data> dagrun:<DagRun scrape_and_store_airbnb_data @ 2024-11-20 21:30:27.250542+00:00: manual__2024-11-20T21:30:27.250542+00:00, state:running, queued_at: 2024-11-20 21:45:14.397794+00:00. externally triggered: True>
[2024-11-20T21:45:31.498+0000] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2024-11-20T21:45:31.498+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=scrape_and_store_airbnb_data, task_id=scrape_airbnb_data, run_id=manual__2024-11-20T21:30:27.250542+00:00, execution_date=20241120T213027, start_date=20241120T214516, end_date=20241120T214531
[2024-11-20T21:45:31.508+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-20T21:45:31.533+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=181, status='terminated', exitcode=2, started='21:45:15') (181) terminated with exit code 2
